version: '3.7'

services:
  budget_bot_service:
    build:
      context: .
      dockerfile: system/Dockerfile
    command: system/entry_point_run_bot.sh
    ports:
      - "8001:8001"
    depends_on:
      - postgers

  postgers:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=telegram_bot
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telegram_bot
    ports:
      - "7434:5432"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./system/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - budget_bot_service

