CURRENCIES = [
    "USD",
    "EUR",
]

EXPENSE_CATEGORY_GROCERIES = 0
EXPENSE_CATEGORY_RESTAURANTS = 1
EXPENSE_CATEGORY_SHOPPING = 2
EXPENSE_CATEGORY_TRANSPORTATION = 3
EXPENSE_CATEGORY_ENTERTAINMENT = 4
EXPENSE_CATEGORY_HEALTH = 5
EXPENSE_CATEGORY_SERVICES = 6
EXPENSE_CATEGORY_GIFTS = 7
EXPENSE_CATEGORY_OTHERS = 8

EXPENSE_CATEGORIES = [
    EXPENSE_CATEGORY_GROCERIES,
    EXPENSE_CATEGORY_RESTAURANTS,
    EXPENSE_CATEGORY_SHOPPING,
    EXPENSE_CATEGORY_TRANSPORTATION,
    EXPENSE_CATEGORY_ENTERTAINMENT,
    EXPENSE_CATEGORY_HEALTH,
    EXPENSE_CATEGORY_SERVICES,
    EXPENSE_CATEGORY_GIFTS,
    EXPENSE_CATEGORY_OTHERS,
]

DISPLAY_EXPENSE_CATEGORIES = {
    EXPENSE_CATEGORY_GROCERIES: 'groceries',
    EXPENSE_CATEGORY_RESTAURANTS: 'restaurants',
    EXPENSE_CATEGORY_SHOPPING: 'shopping',
    EXPENSE_CATEGORY_TRANSPORTATION: 'transportation',
    EXPENSE_CATEGORY_ENTERTAINMENT: 'entertainment',
    EXPENSE_CATEGORY_HEALTH: 'health',
    EXPENSE_CATEGORY_SERVICES: 'services',
    EXPENSE_CATEGORY_GIFTS: 'gifts',
    EXPENSE_CATEGORY_OTHERS: 'others',
}
